In [1]:
import numpy as np

In [2]:
#Numpy - Array Manipulation.

In [3]:
arr = np.random.randint(1,10 , (4,4))

In [4]:
arr

array([[1, 1, 9, 3],
       [7, 5, 4, 7],
       [8, 2, 3, 5],
       [5, 8, 4, 9]])

In [6]:
arr.reshape(8,2)

array([[1, 1],
       [9, 3],
       [7, 5],
       [4, 7],
       [8, 2],
       [3, 5],
       [5, 8],
       [4, 9]])

In [7]:
arr

array([[1, 1, 9, 3],
       [7, 5, 4, 7],
       [8, 2, 3, 5],
       [5, 8, 4, 9]])

In [8]:
arr.T

array([[1, 7, 8, 5],
       [1, 5, 2, 8],
       [9, 4, 3, 4],
       [3, 7, 5, 9]])

In [9]:
arr.flatten()

array([1, 1, 9, 3, 7, 5, 4, 7, 8, 2, 3, 5, 5, 8, 4, 9])

In [10]:
arr

array([[1, 1, 9, 3],
       [7, 5, 4, 7],
       [8, 2, 3, 5],
       [5, 8, 4, 9]])

In [11]:
np.expand_dims(arr,axis=1)

array([[[1, 1, 9, 3]],

       [[7, 5, 4, 7]],

       [[8, 2, 3, 5]],

       [[5, 8, 4, 9]]])

In [12]:
np.expand_dims(arr,axis=0)

array([[[1, 1, 9, 3],
        [7, 5, 4, 7],
        [8, 2, 3, 5],
        [5, 8, 4, 9]]])

In [13]:
data = np.array([[1] , [2] , [3]])

In [14]:
np.squeeze(data)

array([1, 2, 3])

In [15]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [16]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [17]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [18]:
#Numpy - Binary Operators

In [19]:
arr1 = np.random.randint(1,10 , (3,4))
arr2 = np.random.randint(1,10 , (3,4))

In [20]:
arr2

array([[2, 8, 5, 8],
       [9, 1, 6, 8],
       [6, 4, 5, 9]])

In [22]:
arr1

array([[9, 8, 9, 2],
       [3, 1, 6, 6],
       [8, 9, 2, 7]])

In [23]:
arr1+arr2

array([[11, 16, 14, 10],
       [12,  2, 12, 14],
       [14, 13,  7, 16]])

In [24]:
arr1*arr2

array([[18, 64, 45, 16],
       [27,  1, 36, 48],
       [48, 36, 10, 63]])

In [25]:
arr1/arr2

array([[4.5       , 1.        , 1.8       , 0.25      ],
       [0.33333333, 1.        , 1.        , 0.75      ],
       [1.33333333, 2.25      , 0.4       , 0.77777778]])

In [26]:
arr1-arr2

array([[ 7,  0,  4, -6],
       [-6,  0,  0, -2],
       [ 2,  5, -3, -2]])

In [27]:
arr1**arr2

array([[      81, 16777216,    59049,      256],
       [   19683,        1,    46656,  1679616],
       [  262144,     6561,       32, 40353607]])

In [29]:
~arr1 #####doubt

array([[-10,  -9, -10,  -3],
       [ -4,  -2,  -7,  -7],
       [ -9, -10,  -3,  -8]])

In [30]:
arr1

array([[9, 8, 9, 2],
       [3, 1, 6, 6],
       [8, 9, 2, 7]])

In [31]:
arr1>arr2

array([[ True, False,  True, False],
       [False, False, False, False],
       [ True,  True, False, False]])

In [32]:
#Numpy - String Functions.

In [33]:
arr = np.array(["sudh" , "kumar"])

In [34]:
arr

array(['sudh', 'kumar'], dtype='<U5')

In [35]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [36]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [37]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [38]:
#Numpy - Mathematical Functions.

In [39]:
arr1

array([[9, 8, 9, 2],
       [3, 1, 6, 6],
       [8, 9, 2, 7]])

In [40]:
np.sin(arr1)

array([[ 0.41211849,  0.98935825,  0.41211849,  0.90929743],
       [ 0.14112001,  0.84147098, -0.2794155 , -0.2794155 ],
       [ 0.98935825,  0.41211849,  0.90929743,  0.6569866 ]])

In [41]:
np.cos(arr1)

array([[-0.91113026, -0.14550003, -0.91113026, -0.41614684],
       [-0.9899925 ,  0.54030231,  0.96017029,  0.96017029],
       [-0.14550003, -0.91113026, -0.41614684,  0.75390225]])

In [42]:
np.tan(arr1)

array([[-0.45231566, -6.79971146, -0.45231566, -2.18503986],
       [-0.14254654,  1.55740772, -0.29100619, -0.29100619],
       [-6.79971146, -0.45231566, -2.18503986,  0.87144798]])

In [43]:
np.log10(arr1)

array([[0.95424251, 0.90308999, 0.95424251, 0.30103   ],
       [0.47712125, 0.        , 0.77815125, 0.77815125],
       [0.90308999, 0.95424251, 0.30103   , 0.84509804]])

In [44]:
np.exp(arr1)

array([[8.10308393e+03, 2.98095799e+03, 8.10308393e+03, 7.38905610e+00],
       [2.00855369e+01, 2.71828183e+00, 4.03428793e+02, 4.03428793e+02],
       [2.98095799e+03, 8.10308393e+03, 7.38905610e+00, 1.09663316e+03]])

In [45]:
np.power(arr1,2)

array([[81, 64, 81,  4],
       [ 9,  1, 36, 36],
       [64, 81,  4, 49]])

In [46]:
np.mean(arr1
       )

5.833333333333333

In [47]:
np.median(arr1)

6.5

In [48]:
np.std(arr1)

2.9107081994288304

In [49]:
np.var(arr1)

8.472222222222223

In [50]:
np.min(arr1)

1

In [51]:
np.max(arr1)

9

In [52]:
#Numpy - Arithmetic Operations.

In [53]:
arr1

array([[9, 8, 9, 2],
       [3, 1, 6, 6],
       [8, 9, 2, 7]])

In [54]:
arr2

array([[2, 8, 5, 8],
       [9, 1, 6, 8],
       [6, 4, 5, 9]])

In [55]:
arr1-arr2

array([[ 7,  0,  4, -6],
       [-6,  0,  0, -2],
       [ 2,  5, -3, -2]])

In [56]:
np.subtract(arr1,arr2)

array([[ 7,  0,  4, -6],
       [-6,  0,  0, -2],
       [ 2,  5, -3, -2]])

In [57]:
np.multiply(arr1,arr2)

array([[18, 64, 45, 16],
       [27,  1, 36, 48],
       [48, 36, 10, 63]])

In [58]:
np.mod(arr1,arr2)

array([[1, 0, 4, 2],
       [3, 0, 0, 6],
       [2, 1, 2, 7]])

In [59]:
np.power(arr1,arr2)

array([[      81, 16777216,    59049,      256],
       [   19683,        1,    46656,  1679616],
       [  262144,     6561,       32, 40353607]])

In [60]:
np.sqrt(arr1)

array([[3.        , 2.82842712, 3.        , 1.41421356],
       [1.73205081, 1.        , 2.44948974, 2.44948974],
       [2.82842712, 3.        , 1.41421356, 2.64575131]])

In [61]:
#Numpy - Statistical Functions.

In [62]:
arr1

array([[9, 8, 9, 2],
       [3, 1, 6, 6],
       [8, 9, 2, 7]])

In [63]:
np.mean(arr1)

5.833333333333333

In [64]:
np.std(arr1)

2.9107081994288304