In [1]:
##Sort, Search & Counting Functions.

In [2]:
import numpy as np

In [3]:
arr = np.array([4,2,8,5,3,9,12,56])

In [4]:
arr

array([ 4,  2,  8,  5,  3,  9, 12, 56])

In [5]:
np.sort(arr)

array([ 2,  3,  4,  5,  8,  9, 12, 56])

In [6]:
np.searchsorted(arr,6)

5

In [7]:
arr1 = np.array([0,324,645,65,6,6,0,0,0,234])

In [8]:
np.count_nonzero(arr1)

6

In [9]:
np.where(arr1 > 0 )

(array([1, 2, 3, 4, 5, 9]),)

In [10]:
np.extract(arr1 >2,arr1)

array([324, 645,  65,   6,   6, 234])

In [11]:
#Numpy - Byte Swapping.

In [12]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [13]:
arr.byteswap(True)

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [14]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [15]:
arr

array([ 288230376151711744,  144115188075855872,  576460752303423488,
        360287970189639680,  216172782113783808,  648518346341351424,
        864691128455135232, 4035225266123964416])

In [16]:
#Numpy - Copies &Views.

In [18]:
arr1

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])

In [19]:
a = np.copy(arr1)

In [20]:
b = arr1.view()

In [21]:
b = arr1

In [22]:
b

array([  0, 324, 645,  65,   6,   6,   0,   0,   0, 234])