In [1]:
import numpy as np

In [2]:
l = [1,2,3,4,5]

In [3]:
arr = np.array(l)

In [4]:
type(arr)

numpy.ndarray

In [5]:
np.asarray(l)

array([1, 2, 3, 4, 5])

In [6]:
arr1 = np.array([[1,2,3] , [2,3,4]])

In [7]:
arr.ndim

1

In [8]:
arr.ndim

1

In [9]:
arr

array([1, 2, 3, 4, 5])

In [11]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
mat = np.matrix(l)

In [13]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [14]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [15]:
arr

array([1, 2, 3, 4, 5])

In [16]:
a = arr

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
arr

array([1, 2, 3, 4, 5])

In [19]:
arr[0] = 100 ## swollow copy

In [20]:
arr

array([100,   2,   3,   4,   5])

In [21]:
a

array([100,   2,   3,   4,   5])

In [22]:
b = np.copy(arr)

In [23]:
b

array([100,   2,   3,   4,   5])

In [25]:
arr

array([100,   2,   3,   4,   5])

In [26]:
np.fromfunction(lambda i,j : i==j , (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])