In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0.4,10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
list(np.arange(.4 , 10.4 , 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [6]:
np.linspace(1,5 , 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [7]:
np.logspace(1,5 , 10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
arr = np.ones((3,4))

In [14]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
arr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [16]:
arr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [17]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [18]:
arr1 = np.eye(5)

In [19]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
import pandas as pd 

In [21]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [22]:
np.random.rand(2,3)

array([[0.25956349, 0.30217362, 0.89016303],
       [0.07108898, 0.07370416, 0.17836774]])

In [23]:
np.random.randn(2,3)

array([[ 1.98467915,  0.03667102,  1.16853518],
       [ 0.28199292,  1.12589344, -0.60126883]])

In [24]:
arr2 = np.random.randint(1,5 , (3,4))

In [25]:
arr2

array([[4, 1, 3, 1],
       [4, 3, 2, 4],
       [3, 4, 3, 2]])

In [26]:
arr2.reshape(6,2)

array([[4, 1],
       [3, 1],
       [4, 3],
       [2, 4],
       [3, 4],
       [3, 2]])

In [27]:
arr2.reshape(2,6)

array([[4, 1, 3, 1, 4, 3],
       [2, 4, 3, 4, 3, 2]])

In [28]:
arr2.reshape(4,3)

array([[4, 1, 3],
       [1, 4, 3],
       [2, 4, 3],
       [4, 3, 2]])

In [29]:
arr2.reshape(4,-1)

array([[4, 1, 3],
       [1, 4, 3],
       [2, 4, 3],
       [4, 3, 2]])

In [30]:
arr2.reshape(4,-1432453453)

array([[4, 1, 3],
       [1, 4, 3],
       [2, 4, 3],
       [4, 3, 2]])

In [31]:
arr2.reshape(2,2,3,1,1,1)

array([[[[[[4]]],


         [[[1]]],


         [[[3]]]],



        [[[[1]]],


         [[[4]]],


         [[[3]]]]],




       [[[[[2]]],


         [[[4]]],


         [[[3]]]],



        [[[[4]]],


         [[[3]]],


         [[[2]]]]]])

In [32]:
arr1 = np.random.randint(1,10 , (5,6))

In [33]:
arr1

array([[8, 5, 8, 3, 8, 4],
       [7, 8, 8, 1, 4, 6],
       [8, 6, 8, 7, 2, 1],
       [3, 5, 7, 9, 9, 6],
       [7, 8, 4, 1, 2, 8]])

In [34]:
arr1 >8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True,  True, False],
       [False, False, False, False, False, False]])

In [35]:
arr1[arr1 >8]

array([9, 9])

In [36]:
arr1

array([[8, 5, 8, 3, 8, 4],
       [7, 8, 8, 1, 4, 6],
       [8, 6, 8, 7, 2, 1],
       [3, 5, 7, 9, 9, 6],
       [7, 8, 4, 1, 2, 8]])

In [37]:
arr1[0,[0,1]]

array([8, 5])

In [38]:
arr1[2:4 , [2,3]]

array([[8, 7],
       [7, 9]])

In [39]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [40]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 2, 2]])

In [41]:
arr2

array([[2, 2, 2],
       [1, 1, 1],
       [1, 2, 1]])

In [42]:
arr1+arr2

array([[3, 3, 3],
       [2, 2, 2],
       [2, 4, 3]])

In [43]:
arr1-arr2

array([[-1, -1, -1],
       [ 0,  0,  0],
       [ 0,  0,  1]])

In [44]:
arr1*arr2

array([[2, 2, 2],
       [1, 1, 1],
       [1, 4, 2]])

In [45]:
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 2, 2]])

In [46]:
arr2

array([[2, 2, 2],
       [1, 1, 1],
       [1, 2, 1]])

In [47]:
arr1@arr2  ## Matrix multiplication

array([[4, 5, 4],
       [4, 5, 4],
       [6, 8, 6]])

In [48]:
 arr1/arr2

array([[0.5, 0.5, 0.5],
       [1. , 1. , 1. ],
       [1. , 1. , 2. ]])

In [49]:
arr1/0

/tmp/ipykernel_650/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [50]:
#Numpy – Broadcasting.

In [51]:
arr = np.zeros((3,4))

In [52]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [54]:
a = np.array([1,2,3,4])

In [56]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [57]:
b = np.array([[3,4,5]])

In [58]:
arr1 = arr+b.T

In [59]:
b.T

array([[3],
       [4],
       [5]])

In [60]:
arr1

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [61]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.73205081, 1.73205081],
       [2.        , 2.        , 2.        , 2.        ],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798]])

In [62]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.47712125, 0.47712125],
       [0.60205999, 0.60205999, 0.60205999, 0.60205999],
       [0.69897   , 0.69897   , 0.69897   , 0.69897   ]])

In [63]:
np.exp(arr1)

array([[ 20.08553692,  20.08553692,  20.08553692,  20.08553692],
       [ 54.59815003,  54.59815003,  54.59815003,  54.59815003],
       [148.4131591 , 148.4131591 , 148.4131591 , 148.4131591 ]])

In [64]:
np.min(arr1)

3.0

In [65]:
np.max(arr1)

5.0