Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.


Yes, there is a difference in the data types of variables list_ and array_list.

list_ is a Python list, while array_list is a NumPy array.

We can print the data types of both variables using the type() function

In [1]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']

# Converting the list to a NumPy array
array_list = np.array(object=list_)

# Printing the data types of both variables
print("Data type of 'list_':", type(list_))
print("Data type of 'array_list':", type(array_list))

Data type of 'list_': <class 'list'>
Data type of 'array_list': <class 'numpy.ndarray'>


# Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [2]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']

array_list = np.array(object=list_)

# Printing the data type of each element in 'list_'
print("Data type of elements in 'list_':")
for element in list_:
    print(type(element))

# Printing the data type of each element in 'array_list'
print("\nData type of elements in 'array_list':")
for element in array_list:
    print(type(element))

Data type of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in 'array_list':
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Q3. Considering the following changes in the variable, array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list due to the specified dtype=int parameter in the np.array() function call. This parameter explicitly converts the elements to integers when creating the NumPy array.

In [4]:
import numpy as np

# Define the list
list_ = ['1', '2', '3', '4', '5']

# Convert the list to a NumPy array with data type set to integer
array_list = np.array(object=list_, dtype=int)

# Print the data type of each element in 'list_'
print("Data type of elements in 'list_':")
for element in list_:
    print(type(element))

# Print the data type of each element in 'array_list'
print("\nData type of elements in 'array_list':")
for element in array_list:
    print(type(element))

Data type of elements in 'list_':
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of elements in 'array_list':
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:
    
import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

# Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape
(ii) size

In [5]:
import numpy as np

num_array = np.array([[1, 2, 3], [4, 5, 6]])


shape = num_array.shape
print("Shape of num_array:", shape)


size = num_array.size
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [6]:
import numpy as np

# Create a NumPy array of zeros with shape (3, 3)
zeros_array = np.zeros((3, 3))

# Print the array
print("Array of zeros:")
print(zeros_array)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [7]:
import numpy as np

# Create an identity matrix of shape (5, 5)
identity_matrix = np.identity(5)

# Print the identity matrix
print("Identity matrix of shape (5, 5):")
print(identity_matrix)


Identity matrix of shape (5, 5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
